// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArGdJx-jQZuSXJ2JPZsSHgfLrIYxFR62g',
    appId: '1:106791476366:web:7c1c27fb381a86de087ddf',
    messagingSenderId: '106791476366',
    projectId: 'abonosapp-6507a',
    authDomain: 'abonosapp-6507a.firebaseapp.com',
    storageBucket: 'abonosapp-6507a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdKkYW9OEiCju29MZdzMVw2-wpODEIFZw',
    appId: '1:41846001618:android:06b38f9327632bc402c20b',
    messagingSenderId: '41846001618',
    projectId: 'restaurant-app-1b5cc',
    storageBucket: 'restaurant-app-1b5cc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnrLmkLIi7AsxZRE2zPNrpO4ZcAb4i9yE',
    appId: '1:106791476366:ios:e357da4340bfd81b087ddf',
    messagingSenderId: '106791476366',
    projectId: 'abonosapp-6507a',
    storageBucket: 'abonosapp-6507a.firebasestorage.app',
    iosBundleId: 'com.example.movil',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAnrLmkLIi7AsxZRE2zPNrpO4ZcAb4i9yE',
    appId: '1:106791476366:ios:e357da4340bfd81b087ddf',
    messagingSenderId: '106791476366',
    projectId: 'abonosapp-6507a',
    storageBucket: 'abonosapp-6507a.firebasestorage.app',
    iosBundleId: 'com.example.movil',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyArGdJx-jQZuSXJ2JPZsSHgfLrIYxFR62g',
    appId: '1:106791476366:web:64882b5995ec4d12087ddf',
    messagingSenderId: '106791476366',
    projectId: 'abonosapp-6507a',
    authDomain: 'abonosapp-6507a.firebaseapp.com',
    storageBucket: 'abonosapp-6507a.firebasestorage.app',
  );

}